3rd step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -10,5 +10,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:  
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
       - name: Bye
         run: "Goodbye"
