addded 10th wflow with needs function

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,7 +1,6 @@
 name: 09 - Using Functions
 
 on:
-  pull_request:
   workflow_dispatch:
 
 jobs:
@@ -22,8 +21,8 @@ jobs:
           echo "I am a bug fix"
       # - name: Sleep for 20 seconds
       #   run: sleep 20s
-      - name: Failing step
-        run: exit 1
+      # - name: Failing step
+      #   run: exit 1
       - name: I will be skipped "always()"
         if: ${{ always() }}
         run: |
